name: Build MicroPython Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential cmake ninja-build ccache dfu-util libffi-dev libssl-dev libusb-1.0-0-dev python3 python3-pip python3-venv

    - name: Clone MicroPython
      run: |
        git clone --depth 1 -b v1.22.0 https://github.com/micropython/micropython.git
        cd micropython
        git submodule update --init lib/pico-sdk || true
        make -C mpy-cross

    - name: Install ESP-IDF & Fix Venv
      run: |
        git clone -b v5.0.2 --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
        cd ~/esp-idf
        ./install.sh esp32s3
        
        # 核心修复：强制忽略系统保护，直接把 pkg_resources 和 ruamel.yaml 灌入乐鑫虚拟环境
        /home/runner/.espressif/python_env/idf5.0_py3.10_env/bin/python -m pip install --ignore-installed "setuptools<70.0.0" ruamel.yaml wheel

    - name: Copy Modules and Build Firmware
      run: |
        source ~/esp-idf/export.sh
        cp -r modules/* micropython/ports/esp32/modules/
        cd micropython/ports/esp32
        make BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT submodules
        make BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: esp32s3-n16r8-frozen-firmware
        path: micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/firmware.bin